GET http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FuZXNoIiwiaWF0IjoxNjA3NzYyNDk0LCJleHAiOjE2MDc3NjI1MTR9.M-cXnjQ8VN5_aoLDiJ91Pzj3qdYSbtAwScQuVAPzdRA

###

POST http://localhost:9000/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FuZXNoIiwiaWF0IjoxNjA3NzU5MTY0fQ.gTh5K5zCkdeIYnbdiWOngUSLdyP9J4-yDGOe-WUn0VI"
}

###
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "username": "ganesh",
    "password": "password"
}

###

DELETE http://localhost:9000/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FuZXNoIiwiaWF0IjoxNjA3NzU5MTY0fQ.gTh5K5zCkdeIYnbdiWOngUSLdyP9J4-yDGOe-WUn0VI"
}

###

POST  http://localhost:9000/users
Content-Type: application/json

{"username":"moin","password":"password", "firstName":"Ganesh", "lastName":"Babu"}

###

POST http://localhost:8000/orders/5fd45d41b4f3e8117034701f
Content-Type: application/json

{"products": [{"title":"Veg Masala Rolls","unit":100},{"title":"Vegetable Briyani","unit":12}],"total": 900}

###


GET http://localhost:8000/orders/5fd45d41b4f3e8117034701f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FuZXNoIiwiaWF0IjoxNjA3NzY3NzM3LCJleHAiOjE2MDc3Njc3NTd9.f5UJz6Y1z3S6C9QgRx42f5RIPcW2aXCtZgzW81Ko8UI
