GET http://localhost:9000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGF1bCIsImlkIjoiNWZkNDVjYWZiNGYzZTgxMTcwMzQ3MDE5IiwiaWF0IjoxNjA3OTY4NTgyLCJleHAiOjE2MDc5Njk0ODJ9.0Bfl1Rp15ydUkDPVo-Ecg3wiJNa5cvfY9bytY98xDHo

###

POST http://localhost:9000/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FuZXNoIiwiaWF0IjoxNjA3NzU5MTY0fQ.gTh5K5zCkdeIYnbdiWOngUSLdyP9J4-yDGOe-WUn0VI"
}

###
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "username": "paul",
    "password": "password"
}

###

DELETE http://localhost:9000/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FuZXNoIiwiaWF0IjoxNjA3NzU5MTY0fQ.gTh5K5zCkdeIYnbdiWOngUSLdyP9J4-yDGOe-WUn0VI"
}

###

POST  http://localhost:9000/users
Content-Type: application/json

{"username":"moin","password":"password", "firstName":"Ganesh", "lastName":"Babu"}

###

POST http://localhost:9000/orders/5fd45d4eb4f3e81170347020
Content-Type: application/json

{"products": [{"title":"Veg Masala Rolls","unit":100},{"title":"Vegetable Briyani","unit":12}],"total": 900}

###


GET http://localhost:9000/orders/5fd45cafb4f3e81170347019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGF1bCIsImlkIjoiNWZkNDVjYWZiNGYzZTgxMTcwMzQ3MDE5IiwiaWF0IjoxNjA3OTY4NTgyLCJleHAiOjE2MDc5Njk0ODJ9.0Bfl1Rp15ydUkDPVo-Ecg3wiJNa5cvfY9bytY98xDHo
